[package]
name = "ianny"
version = "0.1.0-alpha.0"
authors = ["zer0-x"]
edition = "2021"
description = "Desktop utility that helps preventing repetitive strain injuries by keeping track of usage patterns and periodically informing user to take breaks"
readme = "README.md"
homepage = "https://github.com/zer0-x/ianny"
repository = "https://github.com/zer0-x/ianny"
license = "GPL-3.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
gtk-layer-shell = "0.6.1"
relm4 = { version = "0.6.0", features = ["libadwaita", "macros"] }

[dependencies.adw]
package = "libadwaita"
version = "0.4.3"
features = ["v1_3"]

[dependencies.relm4-icons]
package = "relm4-icons"
version = "0.6.0"
features = [
    "eye-open",
]

[build-dependencies]
