[package]
name = "ianny"
version = "0.1.0-alpha.0"
authors = ["zer0-x"]
edition = "2021"
description = "Desktop utility that helps preventing repetitive strain injuries by keeping track of usage patterns and periodically informing user to take breaks"
readme = "README.md"
homepage = "https://github.com/zer0-x/ianny"
repository = "https://github.com/zer0-x/ianny"
license = "GPL-3.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
wayland-client = "0.30.2"
wayland-protocols = { version = "0.30.0", features = ["client", "staging"] }
wayland-protocols-plasma = { version = "0.1.0", features = ["client"] }
single-instance = "0.3.3"
gcd = "2.3.0"
notify-rust = { version = "4.8.0", default-features = false, features = ["d"] }

[build-dependencies]
